# Generated by Django 5.1.1 on 2026-10-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_transaction_transaction_amount_positive"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "-date"], name="home_transa_user_id_339970_idx"
            ),
        ),
    ]
