# Generated by Django 5.1.1 on 2026-10-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_transaction_home_transa_user_id_339970_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reset_code_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
